version: '2.2'

services:
  openhab:
    image: "openhab/openhab:2.4.0-armhf-alpine"
    restart: unless-stopped
    # network_mode: host
    ports:
      - 8081:8080
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./openhab2/openhab_addons:/openhab/addons"
      - "./openhab2/openhab_conf:/openhab/conf"
      - "./openhab2/openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Amsterdam"
  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant
    ports:
      - 8123:8123
    volumes:
      - "./homeassistant:/config"
    environment:
      TZ: Europe/Amsterdam
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
    # volumes:
    #   - "./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
  domoticz:
    image: linuxserver/domoticz:arm32v7-aaed3481-ls14
    ports:
      - 8080:8080
    volumes:
      - "./domoticz/config:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
