version: '2.2'

services:
  homeassistant:
    image: "ghcr.io/home-assistant/raspberrypi4-homeassistant:stable"
    ports:
      - 8123:8123
    volumes:
      - "./homeassistant:/config"
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Europe/Amsterdam
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    ports:
      - 1883:1883
      - 8883:8883
    restart: unless-stopped
