version: '2.2'

services:
  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:stable
    ports:
      - 8123:8123
    volumes:
      - "./homeassistant:/config"
    environment:
      TZ: Europe/Amsterdam
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    ports:
      - 1883:1883
      - 8883:8883
    restart: unless-stopped
  domoticz:
    image: linuxserver/domoticz:arm32v7-aaed3481-ls14
    ports:
      - 8080:8080
    volumes:
      - "./domoticz/config:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
    volumes:
      - "/media/ssd:/home/hikvision/"
      - "/media/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: hikvision
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/hikvision
    restart: always
