- id: dimm_light_tv_on
  alias: Dimm light when tv is turned on
  trigger:
  - platform: state
    entity_id: media_player.tv
    to: 'on'
  condition:
  - condition: state
    entity_id: light.hue_color_lamp_3
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.hue_color_lamp_3
    data:
      brightness: 25
- id: fan_high
  alias: fan high
  condition:
  - condition: state
    entity_id: switch.afzuiging
    state: 'off'
  trigger:
  - platform: numeric_state
    entity_id: luxtronik.warmwater
    below: 50
  action:
    service: switch.turn_on
    entity_id: switch.afzuiging
- id: light_livingroom_on
  alias: turn on light in livingroom
  trigger:
  - platform: state
    entity_id: light.woonkamer
    from: 'off'
    to: 'on'
  action:
    service: light.turn_on
    entity_id: group.non_hue_lights
- id: light_livingroom_off
  alias: turn off light in livingroom
  trigger:
  - platform: state
    entity_id: light.woonkamer
    from: 'on'
    to: 'off'
  action:
    service: light.turn_off
    entity_id: group.non_hue_lights
- id: '1551989773002'
  alias: Fan low
  trigger:
  - above: 55
    entity_id: luxtronik.warmwater
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.afzuiging
    state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.afzuiging
- id: turn_on_office_power
  alias: Turn on office power
  trigger:
  - at: 08:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: switch.turn_on
    entity_id:  group.office
- id: '1573584001607'
  alias: Power off
  condition:
    - condition: time
      after: '20:00:00'
  trigger:
  - entity_id: light.keuken
    from: 'on'
    platform: state
    to: 'off'
  action:
  - entity_id: group.all_lights
    service: light.turn_off
  - entity_id: switch.tv
    service: switch.turn_off
  - entity_id: group.office
    service: switch.turn_off

- alias: "Doorbell Notifications"
  id: 'doorbell_notification'
  trigger:
    platform: state
    entity_id: binary_sensor.doorbell_button
    to: 'on'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.front_door
        filename: !secret snapshot_path
    - service: notify.mobile_app_iphone
      data:
        title: Doorbell
        message: Ding dong! Someone is at the door!
        data:
          url: !secret snapshot_url
          attachment:
            content-type: jpeg
            url: !secret snapshot_url
- id: '1589640222465'
  alias: Turn on TV
  description: ''
  trigger:
  - at: 09:00
    platform: time
  condition: []
  action:
  - entity_id: switch.tv
    service: switch.turn_on
