- id: fan_high
  alias: fan high
  condition:
  - condition: state
    entity_id: switch.afzuiging
    state: 'off'
  trigger:
  - platform: numeric_state
    entity_id: luxtronik.warmwater
    below: 50
  action:
    service: switch.turn_on
    entity_id: switch.afzuiging

- id: '1551989773002'
  alias: Fan low
  trigger:
  - above: 55
    entity_id: luxtronik.warmwater
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.afzuiging
    state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.afzuiging


- id: turn_on_office_power
  alias: Turn on office power
  trigger:
  - at: 08:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: switch.turn_on
    entity_id:  group.office

- id: power_off_switch
  alias: Power off via switch
  trigger:
  - device_id: 34eb5923e9502913a187e9d15344a6ea
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: turn_off
  action:
    - service: light.turn_off
      target:
        entity_id:
          - group.livingroom
          - group.kitchen
    - condition:
      - condition: time
        after: '22:00:00'
    - service: switch.turn_off
      target:
        entity_id:
          - group.office
          - switch.tv

- id: doorbell_notification
  alias: Doorbell notification
  trigger:
    - platform: mqtt
      topic: shellies/doorbell/input/0
      payload: '1'
  # condition:
  #   - condition: template
  #     value_template: >-
  #       {{ (as_timestamp(now()) -
  #       as_timestamp(state_attr('automation.doorbell_notification', 'last_triggered')
  #       | default(0)) | int > 5)}}
  variables:
    secret_dir: !secret secret_dir
    snapshot_url: !secret snapshot_url
    filename: "{{ now().strftime('%Y%m%d%H%M%S') }}.jpg"
    snapshot_path: "/config/www/{{ secret_dir }}/{{ filename }}"
    url: "{{ snapshot_url }}/{{ secret_dir }}/{{ filename }}"
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.front_door
        filename: "{{ snapshot_path }}"
    - service: notify.notify
      data:
        title: Doorbell
        message: Ding dong! Someone is at the door!
        data:
          url: "{{ url }}"
          attachment:
            content-type: jpeg
            url: "{{ url }}"

- id: short_press_turn_on
  alias: kitchen light on
  trigger:
  - device_id: 34eb5923e9502913a187e9d15344a6ea
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  action:
    - entity_id: group.kitchen
      service: light.turn_on

- id: short_press_turn_off
  alias: kitchen lights off
  trigger:
  - device_id: 34eb5923e9502913a187e9d15344a6ea
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_off
  action:
    - entity_id: group.kitchen
      service: light.turn_off

- id: long_press_turn_on
  alias: kitchen and livingroom on
  trigger:
  - device_id: 34eb5923e9502913a187e9d15344a6ea
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: turn_on
  action:
    - entity_id: group.kitchen
      service: light.turn_on
    - entity_id: group.livingroom
      service: light.turn_on

- id: lights_on_sunset
  alias: Lights on sunset
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: light.turn_on
      entity_id: group.livingroom
    - service: light.turn_on
      entity_id: group.kitchen

- id: lights_off
  alias: Lights off
  trigger:
    - platform: time
      at: '22:30:00'
  action:
    - service: light.turn_off
      target:
        entity_id:
          - group.livingroom
          - group.kitchen
    - service: switch.turn_off
      target:
        entity_id:
          - group.office
          - switch.tv
