homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.04844495133844
  longitude: 5.628085176611849
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  country: NL
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
  allowlist_external_dirs:
    - /tmp

http:
  use_x_forwarded_for: true
  trusted_proxies:
   - 192.168.1.5

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:

        #device_tracker:
        #- platform: nmap_tracker
        #hosts: 192.168.1.0/24
        #home_interval: 10
        #new_device_defaults:
        #track_new_devices: False
        #exclude:
        #- 192.168.1.5
        #- 192.168.1.1
        #- 192.168.1.15
        #- 192.168.1.11


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    domains:
      - luxtronik

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

mobile_app:

zone:
  - name: Home
    latitude: 52.04844495133844
    longitude: 5.628085176611849
    radius: 100

recorder:
  purge_keep_days: 5

system_health:

luxtronik:
  host: "192.168.1.20"
  port: 8889

stream:

energy:

zha:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
mqtt:  !include mqtt.yaml
