- platform: luxtronik
  scan_interval: 60
  sensors:
    - id: 'ID_WEB_Temperatur_TVL'
      friendly_name: Aanvoer
    - id: 'ID_WEB_Temperatur_TRL'
      friendly_name: Retour
    - id: 'ID_WEB_Temperatur_TBW'
      friendly_name: Warmwater
    - id: 'ID_WEB_Temperatur_TWE'
      friendly_name: Bron in
    - id: 'ID_WEB_Temperatur_TWA'
      friendly_name: Bron uit
    - id: 'ID_WEB_Temperatur_TA'
      friendly_name: Buiten
    - id: 'ID_WEB_HauptMenuStatus_Zeile3'
      friendly_name: Status
    - id: 'ID_WEB_WMZ_Seit'
      friendly_name: Totaal

- platform: rest
  scan_interval: 60
  resource: http://domoticz:8080/json.htm?type=devices&rid=1
  name: 'current power'
  value_template: '{{ value_json.result[0].Usage.rstrip("Watt") | int }}'
  unit_of_measurement: "W"
  device_class: power
- platform: rest
  scan_interval: 60
  resource: http://domoticz:8080/json.htm?type=devices&rid=1
  name: 'current generation'
  value_template: '{{ value_json.result[0].UsageDeliv.rstrip("Watt") | int }}'
  unit_of_measurement: "W"
  device_class: power
- platform: rest
  scan_interval: 60
  resource: http://domoticz:8080/json.htm?type=devices&rid=1
  name: 'total used today'
  value_template: '{{ value_json.result[0].CounterToday.rstrip("kWh") | float }}'
  unit_of_measurement: "kW"
  device_class: power
- platform: rest
  scan_interval: 60
  resource: http://domoticz:8080/json.htm?type=devices&rid=1
  name: 'total delivered today'
  value_template: '{{ value_json.result[0].CounterDelivToday.rstrip("kWh") | float }}'
  unit_of_measurement: "kW"
  device_class: power
