# Weather prediction
- platform: yr

- platform: luxtronik
  scan_interval: 60
  sensors:
    - id: 'ID_WEB_Temperatur_TVL'
      friendly_name: Aanvoer temperatuur
    - id: 'ID_WEB_Temperatur_TRL'
      friendly_name: Retour temperatuur
    - id: 'ID_WEB_Temperatur_TBW'
      friendly_name: temperatuur

- platform: rest
  resource: http://openhab:8080/rest/items/HeatPump_Temperature_6
  name: 'temp. warmwater'
  value_template: '{{ value_json.state }}'
  unit_of_measurement: "°C"
  verify_ssl: false
- platform: rest
  resource: http://openhab:8080/rest/items/HeatPump_Temperature_1
  name: 'Buiten temp.'
  value_template: '{{ value_json.state }}'
  unit_of_measurement: "°C"
  verify_ssl: false
- platform: rest
  resource: http://openhab:8080/rest/items/HeatPump_Probe_in
  name: 'Bron in temp.'
  value_template: '{{ value_json.state }}'
  unit_of_measurement: "°C"
  verify_ssl: false
