# Weather prediction
- platform: yr

  #- platform: luxtronik
  #sensors:
  #  - 'ID_WEB_Temperatur_TVL'
  #- platform: mqtt
  #  name: "Temperature badkamer"
  #  state_topic: "tele/sonoff_badkamer/SENSOR"
  #  value_template: "{{ value_json['SI7021'].Temperature }}"
  #  unit_of_measurement: "째C"
  #- platform: mqtt
  #  name: "Humidity badkamer"
  #  state_topic: "tele/sonoff_badkamer/SENSOR"
  #  value_template: "{{ value_json['SI7021'].Humidity }}"
  #  unit_of_measurement: "%"
- platform: rest
  resource: https://192.168.1.5:8443/rest/items/HeatPump_Temperature_6
  name: 'temp. warmwater'
  value_template: '{{ value_json.state }}'
  unit_of_measurement: "째C"
  verify_ssl: false
- platform: rest
  resource: https://192.168.1.5:8443/rest/items/HeatPump_Temperature_1
  name: 'Buiten temp.'
  value_template: '{{ value_json.state }}'
  unit_of_measurement: "째C"
  verify_ssl: false
- platform: rest
  resource: https://192.168.1.5:8443/rest/items/HeatPump_Probe_in
  name: 'Bron in temp.'
  value_template: '{{ value_json.state }}'
  unit_of_measurement: "째C"
  verify_ssl: false
- platform: rest
  resource: https://192.168.1.5:8443/rest/items/PV_Power_Day
  name: 'Solar totaal'
  value_template: '{{ value_json.state[:-3] }}'
  unit_of_measurement: "kWh"
  verify_ssl: false
