# Weather prediction
- platform: yr

- platform: luxtronik
  scan_interval: 60
  sensors:
    - id: 'ID_WEB_Temperatur_TVL'
      friendly_name: Aanvoer
    - id: 'ID_WEB_Temperatur_TRL'
      friendly_name: Retour
    - id: 'ID_WEB_Temperatur_TBW'
      friendly_name: Warmwater
    - id: 'ID_WEB_Temperatur_TWE'
      friendly_name: Bron in
    - id: 'ID_WEB_Temperatur_TWA'
      friendly_name: Bron uit
    - id: 'ID_WEB_Temperatur_TA'
      friendly_name: Buiten

- platform: rest
  scan_interval: 60
  resource: http://domoticz:8080/json.htm?type=devices&rid=1
  name: 'current power'
  value_template: '{{ value_json.result[0].Usage }}'
  unit_of_measurement: "Watt"
