- platform: luxtronik
  scan_interval: 60
  sensors:
    - id: 'ID_WEB_Temperatur_TVL'
      group: calculations
      friendly_name: Aanvoer
    - id: 'ID_WEB_Temperatur_TRL'
      group: calculations
      friendly_name: Retour
    - id: 'ID_WEB_Temperatur_TBW'
      group: calculations
      friendly_name: Warmwater
    - id: 'ID_WEB_Temperatur_TWE'
      group: calculations
      friendly_name: Bron in
    - id: 'ID_WEB_Temperatur_TWA'
      group: calculations
      friendly_name: Bron uit
    - id: 'ID_WEB_Temperatur_TA'
      group: calculations
      friendly_name: Buiten
    - id: 'ID_WEB_HauptMenuStatus_Zeile3'
      group: calculations
      friendly_name: Status
    - id: 'ID_WEB_WMZ_Seit'
      group: calculations
      friendly_name: Totaal

- platform: template
  sensors:
    pv_2_temperature:
      value_template: '{{ states.sensor.inverter_93000.attributes.tempperature }}'
      unit_of_measurement: 'C'
      friendly_name: "PV 2 Temperature"
      device_class: energy
    pv_2_eday:
      value_template: '{{ states.sensor.inverter_93000.attributes.eday }}'
      unit_of_measurement: 'kWh'
      friendly_name: "PV 2 energy day"
      device_class: energy
    pv_2_etotal:
      value_template: '{{ states.sensor.inverter_93000.attributes.etotal }}'
      unit_of_measurement: 'kWh'
      friendly_name: "PV 2 energy total"
      device_class: energy
    pv_2_iday:
      value_template: '{{ states.sensor.inverter_93000.attributes.iday }}'
      unit_of_measurement: '€'
      friendly_name: "PV 2 income day"
      device_class: energy
    pv_2_itotal:
      value_template: '{{ states.sensor.inverter_93000.attributes.itotal }}'
      unit_of_measurement: '€'
      friendly_name: "PV 2 income total"
      device_class: energy
    pv_2_excess:
      value_template: '{{ states.sensor.inverter_93000.attributes.pmeter }}'
      unit_of_measurement: 'W'
      friendly_name: "PV 2 spare"
      device_class: energy

- platform: template
  sensors:
    pv_1_temperature:
      value_template: '{{ states.sensor.inverter_15000.attributes.tempperature }}'
      unit_of_measurement: 'C'
      friendly_name: "PV 1 Temperature"
      device_class: energy
    pv_1_eday:
      value_template: '{{ states.sensor.inverter_15000.attributes.eday }}'
      unit_of_measurement: 'kWh'
      friendly_name: "PV 1 energy day"
      device_class: energy
    pv_1_etotal:
      value_template: '{{ states.sensor.inverter_15000.attributes.etotal }}'
      unit_of_measurement: 'kWh'
      friendly_name: "PV 1 energy total"
      device_class: energy
    pv_1_iday:
      value_template: '{{ states.sensor.inverter_15000.attributes.iday }}'
      unit_of_measurement: '€'
      friendly_name: "PV 1 income day"
      device_class: energy
    pv_1_itotal:
      value_template: '{{ states.sensor.inverter_15000.attributes.itotal }}'
      unit_of_measurement: '€'
      friendly_name: "PV 1 income total"
      device_class: energy
    pv_1_excess:
      value_template: '{{ states.sensor.inverter_15000.attributes.pmeter }}'
      unit_of_measurement: 'W'
      friendly_name: "PV 1 spare"
      device_class: energy

# - platform: integration
#   source: sensor.inverter_93000dsn193w0058
#   name: production_inverter_1
#   unit_prefix: k
#   round: 2

# - platform: integration
#   source: sensor.inverter_none
#   name: production_inverter_2
#   unit_prefix: k
#   round: 2
