- platform: mqtt
  name: "Afzuiging"
  state_topic: "stat/sonoff_afzuiging/POWER"
  command_topic: "cmnd/sonoff_afzuiging/power"
- platform: mqtt
  name: "Office Chris"
  state_topic: "stat/sonoff_office_chris/POWER"
  command_topic: "cmnd/sonoff_office_chris/power"
- platform: mqtt
  name: "Office Mirjam"
  state_topic: "stat/sonoff_xmas_tree/POWER"
  command_topic: "cmnd/sonoff_xmas_tree/power"
- platform: mqtt
  name: "TV"
  state_topic: "stat/sonoff_tv/POWER"
  command_topic: "cmnd/sonoff_tv/power"
